[package]
name = "tcrec"
version = "0.9.0"
authors = ["Denis Rodionov <zunh@protonmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
actix-files = "0.1"
askama = "0.8"
csv = "1.1"
lazy_static = "1.4.0"
Inflector = "0.11.4"